name: Crypto Hunter Bot

on:
  workflow_dispatch: # Чтобы запускать вручную кнопку
  schedule:
    - cron: '0 */6 * * *' # Будет сам перезапускаться каждые 6 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 # ВОТ ИСПРАВЛЕННАЯ СТРОКА!
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eth-account mnemonic requests web3

      - name: Run Hunter
        run: python hunter.py
